project:
  type: website
  output-dir: docs

website:
  title: "Pranav Polepaka"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
      - certifications.qmd

format:
  html:
    theme: 
      light: minty
      dark: solar
    css: styles.css
    toc: true
    page-layout: full


