project:
  type: website
  output-dir: docs

website:
  title: "Pranav Polepaka"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - sidebar:projects.qmd
      - codes.qmd
      - certifications.qmd
      
      
   sidebar:
    - id: projects
      title: "Projects"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
  
      

format:
  html:
    theme: 
      light: minty
      dark: solar
    css: styles.css
    toc: true
    page-layout: full


